// @vitest-environment happy-dom
import { act, createElement } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { SharedMemoryPanel } from "../SharedMemoryPanel";
import type { MemoryDetail, MemoryEntry, MemoryRevision } from "../types";
import type { Run } from "@/features/runs/types";

const mock=vi.hoisted(()=>({list:vi.fn(),get:vi.fn(),propose:vi.fn(),decide:vi.fn(),promote:vi.fn(),facts:vi.fn(),snapshot:vi.fn(),listen:vi.fn()}));
vi.mock("../ipc",()=>({listMemory:mock.list,getMemory:mock.get,proposeMemory:mock.propose,decideMemory:mock.decide,promoteFact:mock.promote,listRunFacts:mock.facts,listMemorySnapshot:mock.snapshot}));
vi.mock("@tauri-apps/api/event",()=>({listen:mock.listen}));
vi.mock("neogestify-ui-components",()=>({Button:({children,onClick,disabled}: {children: React.ReactNode;onClick?:()=>void;disabled?:boolean})=>createElement("button",{onClick,disabled},children)}));

const entry: MemoryEntry={id:"e1",scope:"workspace",workspaceId:"w1",missionId:null,key:"architecture",kind:"note",status:"active",currentRevision:1,priority:0,body:"SQLite",authorKind:"user",sourceRunId:null,sourceTaskId:null,sourceFactId:null,createdAt:1,updatedAt:1,pendingRevision:null,pendingOperation:null,pendingKind:null,pendingPriority:null,pendingBody:null,pendingActorKind:null,pendingSourceRunId:null,pendingSourceTaskId:null,pendingSourceFactId:null,pendingReason:null,pendingCreatedAt:null};
const pending: MemoryEntry={...entry,pendingRevision:2,pendingOperation:"update",pendingBody:"Postgres",pendingActorKind:"worker",pendingPriority:2,pendingKind:"decision"};
const revision: MemoryRevision={entryId:"e1",revision:1,status:"approved",operation:"create",kind:"note",priority:0,body:"SQLite",contentHash:"hash",actorKind:"user",sourceRunId:"r1",sourceTaskId:"t1",sourceFactId:"f1",reason:"keep",expectedRevision:null,createdAt:1,decidedAt:2};
const run={id:"r1",missionId:"m1",status:"done"} as Run;
let root:Root,container:HTMLDivElement;
const render=async(props:Partial<Parameters<typeof SharedMemoryPanel>[0]>={})=>{await act(async()=>{root.render(createElement(SharedMemoryPanel,{workspaceId:"w1",...props}));});};
const click=async(text:string)=>{const button=[...container.querySelectorAll("button")].find(b=>b.textContent===text);expect(button,`button ${text}`).toBeTruthy();await act(async()=>{button!.click();});};
const change=async(input:HTMLInputElement|HTMLTextAreaElement,value:string)=>{const prototype=input instanceof HTMLInputElement?HTMLInputElement.prototype:HTMLTextAreaElement.prototype;Object.getOwnPropertyDescriptor(prototype,"value")!.set!.call(input,value);await act(async()=>{input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}));});};
beforeEach(()=>{vi.clearAllMocks();mock.list.mockResolvedValue({items:[entry],hasMore:false,nextCursor:null,truncated:false});mock.get.mockResolvedValue({entry,revisions:[revision]} satisfies MemoryDetail);mock.propose.mockResolvedValue({entryId:"e1",revision:2,status:"proposed",idempotent:false});mock.decide.mockResolvedValue(undefined);mock.promote.mockResolvedValue({entryId:"e1",revision:2});mock.facts.mockResolvedValue([{id:"f1",kind:"finding",body:"Run discovery",createdAt:1,author:"Worker"}]);mock.snapshot.mockResolvedValue({items:[],meta:{contextBytes:0,omittedEntries:0,truncatedEntries:0}});mock.listen.mockResolvedValue(()=>{});container=document.createElement("div");document.body.append(container);root=createRoot(container);
// React test host flag.
Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();});

describe("Shared Memory interface",()=>{
 it("loads the complete body before editing a truncated list preview",async()=>{mock.list.mockResolvedValue({items:[{...entry,body:"preview",bodyTruncated:true}],hasMore:false});await render();expect(container.textContent).toContain("Prévia limitada");await click("Propor edição");expect(mock.get).toHaveBeenCalledWith("e1","w1",null);expect(container.querySelector("textarea")!.value).toBe("SQLite");await click("Enviar proposta");expect(mock.propose).toHaveBeenCalledWith("w1",null,expect.objectContaining({body:"SQLite",operation:"update"}));});
 it("lists workspace and mission memories separately in PT-BR",async()=>{await render({missionId:"m1"});expect(container.textContent).toContain("Memória do Workspace");expect(container.textContent).toContain("Memória da Mission");expect(container.textContent).toContain("SQLite");expect(mock.list).toHaveBeenCalledWith("w1",null);expect(mock.list).toHaveBeenCalledWith("w1","m1");});
 it.each([true,false])("decides pending proposal with approve=%s",async(approve)=>{mock.list.mockResolvedValue({items:[pending],hasMore:false});await render();expect(container.textContent).toContain("Proposta de atualização");expect(container.textContent).toContain("Postgres");expect(container.textContent).toContain("SQLite");await click(approve?"Aprovar":"Rejeitar");expect(mock.decide).toHaveBeenCalledWith("e1",2,approve);});
 it("edits by creating a revision against the approved version",async()=>{await render();await click("Propor edição");await change(container.querySelector("textarea")!,"New decision");await click("Enviar proposta");expect(mock.propose).toHaveBeenCalledWith("w1",null,expect.objectContaining({operation:"update",expectedRevision:1,key:"architecture",body:"New decision"}));});
 it("proposes a tombstone without deleting history",async()=>{await render();await click("Propor exclusão");expect(container.textContent).toContain("continuará ativa");await click("Enviar proposta");expect(mock.propose).toHaveBeenCalledWith("w1",null,expect.objectContaining({operation:"delete",expectedRevision:1}));});
 it("shows tombstone and history without enabling edit",async()=>{mock.list.mockResolvedValue({items:[{...entry,status:"deleted",currentRevision:null,body:null}],hasMore:false});await render();expect(container.textContent).toContain("Excluída");expect(container.textContent).not.toContain("Propor edição");await click("Ver revisões");expect(container.textContent).toContain("Histórico: architecture");expect(container.textContent).toContain("Aprovada");expect(container.textContent).toContain("Task t1");});
 it("shows the immutable snapshot separately from Run Facts",async()=>{await render({missionId:"m1",runs:[run],activeRunId:"r1"});await click("Snapshot do Run");expect(container.textContent).toContain("Snapshot usado neste Run");expect(container.textContent).toContain("Snapshot vazio");await click("Run Facts");expect(container.textContent).toContain("Run discovery");expect(container.textContent).not.toContain("Snapshot vazio");});
 it("promotes a fact as a pending mission proposal",async()=>{await render({missionId:"m1",runs:[run],activeRunId:"r1"});await click("Run Facts");await click("Propor promoção");await change(container.querySelector('input:not([type="range"])')!,"discovery");await click("Enviar proposta");expect(mock.promote).toHaveBeenCalledWith("r1","f1","mission","discovery",0,undefined);expect(mock.decide).not.toHaveBeenCalled();});
 it("does not offer mission scope without a mission",async()=>{await render();await click("Propor memória");expect(container.querySelector('option[value="mission"]')).toBeNull();});
 it("renders malicious memory as text",async()=>{mock.list.mockResolvedValue({items:[{...entry,key:'<img src=x onerror="alert(1)">',body:'<script>steal()</script>'}],hasMore:false});await render();expect(container.querySelector("script")).toBeNull();expect(container.querySelector("img")).toBeNull();expect(container.textContent).toContain("<script>steal()</script>");});
 it("reloads on memory events without polling",async()=>{await render();const listener=mock.listen.mock.calls.find(([event])=>event==="cc-memory-changed")![1];mock.list.mockResolvedValue({items:[{...entry,body:"New approved content"}],hasMore:false});await act(async()=>listener({payload:null}));expect(container.textContent).toContain("New approved content");});
 it("closes proposal dialog with Escape",async()=>{await render();await click("Propor memória");await act(async()=>document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true})));expect(container.querySelector('[role="dialog"]')).toBeNull();});
});
